website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Producto(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String, nullable=False)
    precio = db.Column(db.Float, nullable=False)
    stock = db.Column(db.Integer, nullable=False)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))

class Venta(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fecha = db.Column(db.DateTime)
    monto = db.Column(db.Float)
    # productos = db.relationship('ProdVendidos', backref='venta', lazy=True)

# class ProdVendidos(db.Model):
#     venta_id = db.Column(db.Integer, db.ForeignKey('venta.id'), nullable=False)
#     producto_id = db.Column(db.Integer, db.ForeignKey('producto.id'), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Producto

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Te logueaste exitosamente!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Contraseña incorrecta, intentalo nuevamente.', category='error')
        else:
            flash('Ese email no existe.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Ya existe una cuenta con ese email.', category='error')
        elif len(email) < 4:
            flash('Ese email no es valido.', category='error')
        elif len(first_name) < 2:
            flash('Ese nombre no es valido.', category='error')
        elif password1 != password2:
            flash('Las contraseñas no coinciden.', category='error')
        elif len(password1) < 7:
            flash('La contraseña es demasiado corta.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Cuenta creada exitosamente!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect
from flask_login import login_required, current_user
from .models import Producto
from . import db
import json, random

jsonText = {
 'Lunes' : 10,
 'Martes' : 11,
 'Miercoles' : 12,
 'Jueves' : 11,
 'Viernes' : 15
}

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
	products = Producto.query.all()
	if request.method == 'POST':
		if request.form.get('add') == 'Agregar':
		    name = request.form.get('Nombre')
		    price = request.form.get('Precio')
		    new = Producto(nombre=name, precio=price, stock=0)
		    db.session.add(new)
		    db.session.commit()
		    flash('Producto Añadido!', category='success')
		elif request.form.get('deleteall') == 'Eliminar':
			for me in products:
				db.session.delete(me)
			db.session.commit()
			flash('Producto Eliminado!', category='success')
		return redirect("/")
	else:
		return render_template("home.html", productos=products, user=current_user, data=jsonText)

@views.route('/delete/<int:id>')
def delete(id):
	borrar = Producto.query.get_or_404(id)
	try:
		db.session.delete(borrar)
		db.session.commit()
		print('Borrado Exitosamente')
	except Exception as e:
		print('Error')
	return redirect("/")

@views.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
	editar = Producto.query.get_or_404(id)
	if request.method == 'POST':
		try:
			editar.nombre = request.form.get('Nombre')
			editar.precio = request.form.get('Precio')
			db.session.commit()
			return redirect("/")
		except Exception as e:
			print('Error')
	else:
		return render_template("edit.html", name=editar.nombre, price=editar.precio, user=current_user, id=id)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Ejemplo de panel de control de ventas">
    <meta name="author" content="Valentino Casadidio">

    <!-- Boostrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Panel de Control{% endblock %}</title>
  </head>
  <body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">Panel</a>
      <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
          {% if user.is_authenticated %}
          <a class="nav-link px-3" href="{{ url_for('auth.logout') }}">Cerrar Sesion</a>
          {% else %}
          <a class="nav-link px-3" href="{{ url_for('auth.login') }}">Iniciar Sesion</a>
          <a class="nav-link px-3" href="{{ url_for('auth.sign_up') }}">Registrarse</a>
          {% endif %}
        </div>
      </div>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}


    <div class="container-fluid">
    
    {% block content %} {% endblock %}

    </div>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="text-muted">© 2021 Company, Inc</span>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/clients.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

website/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div>
	<form method="post" action="/edit/{{ id }}">
		<input type="text" name="Nombre" value="{{ name }}">
		<input type="text" name="Precio" value="{{ price }}">
		<input type="submit" name="edit" value="Editar">
	</form>
</div>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row">

  <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Panel</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Inicio
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Productos
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Clientes
        </a>
      </li>
    </ul>
    <hr>
  </div>

  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Ventas Recientes</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">Compartir</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
        </div>
      </div>
    </div>

    <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="586" height="247" style="display: block; width: 586px; height: 247px;"></canvas>

    <h2>Lista de Productos</h2>
<div class="table-responsive">
  <div>
    <form method="post" action="/">
      <input type="text" name="Nombre">
      <input type="text" name="Precio">
      <input type="submit" name="add" value="Agregar">
      <input type="submit" name="deleteall" value="Eliminar">
    </form>
  </div>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Precio</th>
      </tr>
    </thead>
    <tbody>
      {% for producto in productos %}
      <tr>
        <td>{{ producto.id }}</td>
        <td>{{ producto.nombre }}</td>
        <td>{{ producto.precio }}</td>
        <td><a href="{{ url_for('views.edit', id=producto.id) }}">Editar</a></td>
        <td><a href="{{ url_for('views.delete', id=producto.id) }}">Borrar</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
    
  </main>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='dashboard.js') }}"
></script>
<script type="text/javascript">
  myFunc({{ data|tojson }})
</script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Iniciar Sesion</h3>
  <div class="form-group">
    <label for="email">Direccion de Correo Electronico</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email"
    />
  </div>
  <div class="form-group">
    <label for="password">Contraseña</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Contraseña"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
</form>
{% endblock %}

website/templates/products.html
{% extends 'base.html' %}
{% block content %}
<h2>Lista de Productos</h2>
<div class="table-responsive">
  <div>
    <form method="post" action="/">
      <input type="text" name="Nombre">
      <input type="text" name="Precio">
      <input type="submit" name="add" value="Agregar">
      <input type="submit" name="deleteall" value="Eliminar">
    </form>
  </div>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Precio</th>
      </tr>
    </thead>
    <tbody>
      {% for producto in productos %}
      <tr>
        <td>{{ producto.id }}</td>
        <td>{{ producto.nombre }}</td>
        <td>{{ producto.precio }}</td>
        <td><a href="{{ url_for('views.edit', id=producto.id) }}">Editar</a></td>
        <td><a href="{{ url_for('views.delete', id=producto.id) }}">Borrar</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Registrarse</h3>
  <div class="form-group">
    <label for="email">Direccion de Correo Electronico</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">Nombre</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Nombre"
    />
  </div>
  <div class="form-group">
    <label for="password1">Contraseña</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Contraseña"
    />
  </div>
  <div class="form-group">
    <label for="password2">Contraseña (Confirmar)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Contraseña"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>
{% endblock %}